# -*- coding: utf-8 -*-
"""MultiresUnet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GuLxeclFMO_t0Gk7_D5KJHH65GK8h61V

# MULTIRES-UNET ARCHITECTURE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import tensorflow as tf
import cv2
from keras import layers
from keras.models import Sequential
from keras.models import Input
from keras.models import Model
from keras.layers.convolutional import Conv2D
from keras.layers import Conv2DTranspose
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Activation
from keras.layers import ReLU
from keras.layers import LeakyReLU
from keras.layers import Dropout
from keras.layers import BatchNormalization
from keras.layers import Dropout
from keras.layers import Conv2DTranspose
from keras.layers import UpSampling2D
from keras.layers import MaxPooling2D
from keras.layers import Concatenate
from keras.layers import Reshape
from keras.losses import binary_crossentropy
from keras.layers import add
from keras.utils import plot_model
from keras.optimizers import Adam

imagesize = 256
batch_size = 32

def Multires_Unet_Block(input_data,Number_of_filters):
  filter_scaling_factor = 1.67
  W = filter_scaling_factor * Number_of_filters    # Factor that controls the number of filters and the parameters

  shortcut = Conv2D(int(W*0.167)+int(W*0.333)+int(W*0.5),kernel_size=(1,1),padding='same')(input_data)
  #shortcut = BatchNormalization(axis=3,scale=False)(shortcut)

  D1 = Conv2D(int(W*0.167),kernel_size=(3,3),padding='same',activation='relu')(input_data)
  #D1 = BatchNormalization(axis=3,scale=False)(D1)

  D2 = Conv2D(int(W*0.333),kernel_size=(3,3),padding='same',activation='relu')(D1)
  #D2 = BatchNormalization(axis=3,scale=False)(D2)

  D3 = Conv2D(int(W*0.5),kernel_size=(3,3),padding='same',activation='relu')(D2)
  #D3 = BatchNormalization(axis=3,scale=False)(D3)

  Skip_connect = Concatenate()([D1,D2,D3])
  #Skip_connect = BatchNormalization(axis=3)(Skip_connect)

  D_out = add([shortcut,Skip_connect])
  D_out = Activation('relu')(D_out)
  #D_out = BatchNormalization(axis=3)(D_out)

  return D_out

def Multires_Unet_Path(input_data,Number_of_filters,length_of_path):
  shortcut = Conv2D(Number_of_filters,kernel_size=(1,1),padding='same')(input_data)
  #shortcut = BatchNormalization(axis=3,scale=False)(shortcut)

  P = Conv2D(Number_of_filters,kernel_size=(3,3),padding='same',activation='relu')(input_data)
  #P = BatchNormalization(axis=3,scale=False)(P)

 
  P = add([shortcut,P])
  P = Activation('relu')(P)
  #P = BatchNormalization(axis=3)(P)


  for m in range(length_of_path - 1):
    shortcut = P
    shortcut = Conv2D(Number_of_filters,kernel_size=(1,1),padding='same')(shortcut)
    #shortcut = BatchNormalization(axis=3,scale=False)(shortcut)

    P = Conv2D(Number_of_filters,kernel_size=(3,3),padding='same',activation='relu')(P)
    #P = BatchNormalization(axis=3,scale=False)(P)

    P = add([shortcut,P])
    P = Activation('relu')(P)
    #P = BatchNormalization(axis=3)(P)
  return P

def MultiRes_Unet():
  inputs = Input((imagesize,imagesize,1))

  MSR_block1 = Multires_Unet_Block(inputs,32)
  pool1 = MaxPooling2D(pool_size=(2,2))(MSR_block1)
  MSR_block1 = Multires_Unet_Path(MSR_block1,32,4)


  MSR_block2 = Multires_Unet_Block(pool1,32*2)
  pool2 = MaxPooling2D(pool_size=(2,2))(MSR_block2)
  MSR_block2 = Multires_Unet_Path(MSR_block2,32*2,3)


  MSR_block3 = Multires_Unet_Block(pool2,32*4)
  pool3 = MaxPooling2D(pool_size=(2,2))(MSR_block3)
  MSR_block3 = Multires_Unet_Path(MSR_block3,32*4,2)


  MSR_block4 = Multires_Unet_Block(pool3,32*8)
  pool4 = MaxPooling2D(pool_size=(2,2))(MSR_block4)
  MSR_block4 = Multires_Unet_Path(MSR_block4,32*8,1)


  MSR_block5 = Multires_Unet_Block(pool4,32*16)


  Up6 = Concatenate()([Conv2DTranspose(filters=32*8,kernel_size=(2,2),strides=(2,2),padding='same')(MSR_block5),MSR_block4])
  MSR_block6 = Multires_Unet_Block(Up6,32*8)


  Up7 = Concatenate()([Conv2DTranspose(filters=32*4,kernel_size=(2,2),strides=(2,2),padding='same')(MSR_block6),MSR_block3])
  MSR_block7 = Multires_Unet_Block(Up7,32*4)

  Up8 = Concatenate()([Conv2DTranspose(filters=32*2,kernel_size=(2,2),strides=(2,2),padding='same')(MSR_block7),MSR_block2])
  MSR_block8 = Multires_Unet_Block(Up8,32*2)

  Up9 = Concatenate()([Conv2DTranspose(filters=32,kernel_size=(2,2),strides=(2,2),padding='same')(MSR_block8),MSR_block1])
  MSR_block9 = Multires_Unet_Block(Up9,32)

  output = Conv2D(1,kernel_size=(1,1),activation='sigmoid')(MSR_block9)
  #output = BatchNormalization(axis=3,scale=False)(output)

  model = Model(inputs,output)
  return model

k = MultiRes_Unet()
plot_model(k)