# -*- coding: utf-8 -*-
"""ProposedModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QS9wF54dRWilFn7mw5f0HIc5YoNVM3O4

# PROPOSED MODEL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import tensorflow as tf
import cv2
from keras import layers
from keras.models import Sequential
from keras.models import Input
from keras.models import Model
from keras.layers.convolutional import Conv2D
from keras.layers import Conv2DTranspose
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Activation
from keras.layers import ReLU
from keras.layers import LeakyReLU
from keras.layers import Dropout
from keras.layers import BatchNormalization
from keras.layers import Dropout
from keras.layers import UpSampling2D
from keras.layers import MaxPooling2D
from keras.layers import Concatenate
from keras.layers import Reshape
from keras.losses import binary_crossentropy
from keras.layers import add
from keras.utils import plot_model
from keras.optimizers import Adam

imagesize = 256
batch_size = 32

# Indroduced a Residula plot inplace of a normal Skip connection path.
# To alleviate the problem of Disparity between the Encoder and the Decode.
# Number of parameters
# Unet = 5.4 Million
# MultiRes_Unet = 6.9 Million
# Proposed_model = 8.69 Million

def Proposed_Multires_Unet_Path(input_data,Number_of_filters,length_of_path):
  P = Conv2D(Number_of_filters,kernel_size=(3,3),padding='same',activation='relu')(input_data)
  P = BatchNormalization()(P)
  path_from_input_to_output = Conv2D(Number_of_filters,kernel_size=(1,1),padding='same')(input_data)
  P = add([path_from_input_to_output,P])
  P = Activation('relu')(P)

  for m in range(length_of_path - 1):
    path_from_input_to_output = Conv2D(Number_of_filters,kernel_size=(1,1),padding='same')(P)
    P = BatchNormalization()(P)
    P = Conv2D(Number_of_filters,kernel_size=(3,3),padding='same',activation='relu')(P)
    P = BatchNormalization()(P)
    P = add([path_from_input_to_output,P])
    P = Activation('relu')(P)
  
  return P

def Proposed_Upsample_Block(input_data,skip_connection,Number_of_filters):
  U = UpSampling2D(size=(2,2))(input_data)
  skip_Connect = Concatenate()([U,skip_connection])
  D = BatchNormalization()(skip_Connect)
  D = Conv2D(Number_of_filters,kernel_size=(3,3),activation='relu',padding='same',strides=1)(D)
  D = BatchNormalization()(D)
  D = Conv2D(Number_of_filters,kernel_size=(3,3),activation='relu',padding='same',strides=1)(D)
  D = BatchNormalization()(D)
  return D

def Downsample_Block(input_data,Number_of_filters):
  
  D = Conv2D(Number_of_filters,kernel_size=(3,3),activation='relu',padding='same',strides=1)(input_data)
  D = BatchNormalization()(D)
  D = Conv2D(Number_of_filters,kernel_size=(3,3),activation='relu',padding='same',strides=1)(D)
  P = MaxPooling2D(2)(D)
  return D,P

def Bridge_Block(input_data,Number_of_filters):

  D = Conv2D(Number_of_filters,kernel_size=(3,3),activation='relu',padding='same',strides=1)(input_data)
  D = BatchNormalization()(D)
  D = Conv2D(Number_of_filters,kernel_size=(3,3),activation='relu',padding='same',strides=1)(D)
  return D

def Upsample_Block(input_data,skip_connection,Number_of_filters):
  U = UpSampling2D(size=(2,2))(input_data)
  skip_Connect = Concatenate()([U,skip_connection])
  D = BatchNormalization()(skip_Connect)
  D = Conv2D(Number_of_filters,kernel_size=(3,3),activation='relu',padding='same',strides=1)(D)
  D = BatchNormalization()(D)
  D = Conv2D(Number_of_filters,kernel_size=(3,3),activation='relu',padding='same',strides=1)(D)
  return D

def Proposed_UNET_model():
  filters = [32,64,128,256,512]
  length_of_path = [4,3,2,1]
  inputs = Input((imagesize,imagesize,1))
  A1,P1 = Downsample_Block(inputs,filters[0])
  A2,P2 = Downsample_Block(P1,filters[1])
  A3,P3 = Downsample_Block(P2,filters[2])
  A4,P4 = Downsample_Block(P3,filters[3])

  bridge_output = Bridge_Block(P4,filters[4])
  

  # Addition of Residual path 3
  skip_3 = Proposed_Multires_Unet_Path(A4,filters[3],length_of_path[0])
  U1 = Upsample_Block(bridge_output,skip_3,filters[3])

  # Addition of Residual path 2
  skip_2 = Proposed_Multires_Unet_Path(A3,filters[2],length_of_path[1])
  U2 = Upsample_Block(U1,skip_2,filters[2])

  # Addition of Residual path 1
  skip_1 = Proposed_Multires_Unet_Path(A2,filters[1],length_of_path[2])
  U3 = Upsample_Block(U2,skip_1,filters[1])

  # Addition of Residual path 0
  skip_0 = Proposed_Multires_Unet_Path(A1,filters[0],length_of_path[3])
  U4 = Upsample_Block(U3,skip_0,filters[0])

  output = Conv2D(1,kernel_size=(1,1),activation='sigmoid')(U4)
  model = Model(inputs,output)

  return model

Modified_Unet_model = Proposed_UNET_model()
plot_model(Modified_Unet_model)



